name: news
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  pull_to_refresh_flutter3: ^2.0.2
  webview_flutter: ^4.10.0
  share_plus: ^10.1.3
  
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.2
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
